-- View All Data
SELECT * FROM ENERGY_READINGS ORDER BY TIMESTAMP DESC;

-- Insert Sample Data (Normal Reading)
INSERT INTO ENERGY_READINGS (CURRENT, METER_ID, POWER, THEFT_DETECTED, TIMESTAMP, VOLTAGE) 
VALUES (2.5, 'MTR001', 575.0, FALSE, CURRENT_TIMESTAMP(), 230.0);

-- Insert Sample Data (Theft / High Load)
INSERT INTO ENERGY_READINGS (CURRENT, METER_ID, POWER, THEFT_DETECTED, TIMESTAMP, VOLTAGE) 
VALUES (15.0, 'MTR001', 3450.0, TRUE, CURRENT_TIMESTAMP(), 230.0);

-- Check Theft Alerts
SELECT * FROM ENERGY_READINGS WHERE THEFT_DETECTED = TRUE ORDER BY TIMESTAMP DESC;

-- Get Latest Reading (Same as Dashboard)
SELECT TOP 1 * FROM ENERGY_READINGS ORDER BY TIMESTAMP DESC;

-- Clear All Data (Reset)
DELETE FROM ENERGY_READINGS;
